spring.application.name=portfolio

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-divine-sunset-b34je4cn-pooler.c-4.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_SNG3IgKEPC8v}

spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.path=/docs